# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_ice_platforms_anywhere"

# Version of this mod.
version = "1.1.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Ice Platforms Anywhere"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
Allows ice platforms in Majora's Mask to be created on any body of water in the game. 

In case you don't want every single area in the game to allow ice platform creation, you can specify the areas you do or do not want to allow ice platform creation in by changing the configuration settings of this mod.

NOTE: Ice platforms cannot be created on water that is too shallow.
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Create ice platforms on any body of water!"

# Authors of this mod.
authors = [ "Fenway Powers" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.2"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
# Example dependency:
#    "modname:1.0.0"
]

# Optional dependency mods. This has the same format as `dependencies`, but the game will still start if dependencies in this
# list aren't present. You can query the presence of a given dependency by using `recomp_is_dependency_met` in recomputils.h.
# Calling a function imported from an optional dependency that isn't present will trigger an error.
optional_dependencies = [

]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_ice_platforms_anywhere"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = ["thumb.png"]

[[manifest.config_options]]
id = "allow_anywhere"
name = "Allow Ice Platforms Anywhere"
description = "Determines if ice platforms can be created on any body of water. If set to No, then ice platforms will only be spawnable where they would be in the vanilla game, as well as in any of the scenes you specify should allow ice platform creation."
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"

[[manifest.config_options]]
id = "95"
name = "Allow Ice Platforms in Gyorg's Lair"
description = "Determines if ice platforms can be created in Gyorg's Lair. This replicates the behavior of this scene from the 3DS version of Majora's Mask."
type = "Enum"
options = [ "Yes", "No" ]
default = "Yes"

[[manifest.config_options]]
id = "55"
name = "Allow Ice Platforms in Great Bay Coast (Murky Water)"
description = "Determines if ice platforms can be created in Great Bay Coast when the water is murky (before Gyorg is defeated)."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "51"
name = "Allow Ice Platforms in Zora Hall"
description = "Determines if ice platforms can be created in Zora Hall and the Zora Hall Rooms."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "59"
name = "Allow Ice Platforms in Pirate's Fortress Moat"
description = "Determines if ice platforms can be created in Pirate's Fortress Moat."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "74"
name = "Allow Ice Platforms in the Waterfall Rapids"
description = "Determines if ice platforms can be created in the Waterfall Rapids."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "69"
name = "Allow Ice Platforms in Southern Swamp (poison)"
description = "Determines if ice platforms can be created in Southern Swamp (poison)."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "0"
name = "Allow Ice Platforms in Southern Swamp (clear)"
description = "Determines if ice platforms can be created in Southern Swamp (clear)."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "43"
name = "Allow Ice Platforms in Deku Palace"
description = "Determines if ice platforms can be created in Deku Palace."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "70"
name = "Allow Ice Platforms in Woodfall"
description = "Determines if ice platforms can be created in Woodfall."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "80"
name = "Allow Ice Platforms in Mountain Village (winter)"
description = "Determines if ice platforms can be created in Mountain Village (winter)."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "90"
name = "Allow Ice Platforms in Mountain Village (spring)"
description = "Determines if ice platforms can be created in Mountain Village (spring)."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"

[[manifest.config_options]]
id = "41"
name = "Allow Ice Platforms in Astral Observatory"
description = "Determines if ice platforms can be created in Astral Observatory."
type = "Enum"
options = [ "Yes", "No" ]
default = "No"
